default_platform(:ios)

platform :ios do
  desc "Build for App Store"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "3CL3588VSB",
      issuer_id: "cf8f6456-896e-47ed-a844-e20e07e7126f",
      key_filepath: ENV["KEY_PATH"],
      duration: 1200,
      in_house: false
    )

    sigh(
      api_key: api_key,
      app_identifier: "com.primomarble.daycheckapp",
      output_path: "#{ENV.fetch('RUNNER_TEMP', '/tmp')}/profiles",
      force: true
    )

    update_code_signing_settings(
      use_automatic_signing: false,
      team_id: "K6864D294S",
      bundle_identifier: "com.primomarble.daycheckapp",
      code_sign_identity: "iPhone Distribution",
      profile_uuid: Actions.lane_context[SharedValues::SIGH_UUID],
      path: "ios/PrimoMarble.xcodeproj"
    )

    build_app(
      workspace: "ios/PrimoMarble.xcworkspace",
      scheme: "PrimoMarble",
      configuration: "Release",
      output_directory: "ios/output",
      output_name: "PrimoMarble.ipa",
      export_method: "app-store",
      export_options: {
        teamID: "K6864D294S",
        uploadBitcode: false,
        compileBitcode: false
      }
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "ios/output/PrimoMarble.ipa",
      skip_waiting_for_build_processing: true
    )
  end
end
